title: Lorena Camila Ipanaqué Botton
logo: nueva-carpeta/foto.jpeg
description: ¡Hola! Te doy la bienvenida a mi portafolio de proyectos de QA Engineer.
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
